// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WARestfulAPI.Data;

namespace WARestfulAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210608124912_Shop")]
    partial class Shop
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WARestfulAPI.Modules.Base.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");
                });

            modelBuilder.Entity("WARestfulAPI.Modules.Base.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("WARestfulAPI.Modules.Fruit", b =>
                {
                    b.HasBaseType("WARestfulAPI.Modules.Base.Product");

                    b.HasDiscriminator().HasValue("Fruit");
                });

            modelBuilder.Entity("WARestfulAPI.Modules.Tableware", b =>
                {
                    b.HasBaseType("WARestfulAPI.Modules.Base.Product");

                    b.HasDiscriminator().HasValue("Tableware");
                });

            modelBuilder.Entity("WARestfulAPI.Modules.Vegetable", b =>
                {
                    b.HasBaseType("WARestfulAPI.Modules.Base.Product");

                    b.HasDiscriminator().HasValue("Vegetable");
                });

            modelBuilder.Entity("WARestfulAPI.Modules.Base.Product", b =>
                {
                    b.HasOne("WARestfulAPI.Modules.Base.Shop", "shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shop");
                });
#pragma warning restore 612, 618
        }
    }
}
